-- AlterTable
ALTER TABLE "ContactInquiry" ADD COLUMN IF NOT EXISTS "quotedAmount" DECIMAL(65,30),
ADD COLUMN IF NOT EXISTS "commissionRate" DECIMAL(65,30) DEFAULT 10.00,
ADD COLUMN IF NOT EXISTS "commissionAmount" DECIMAL(65,30),
ADD COLUMN IF NOT EXISTS "notes" TEXT,
ADD COLUMN IF NOT EXISTS "checklist" TEXT;
