name: CI/CD Pipeline - Deploy to Vercel

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  NODE_VERSION: "20"
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  # Lint and Test Job
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: false

      - name: Check code formatting
        run: npx prettier --check .
        continue-on-error: false

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run tests
        run: npx jest --ci --coverage --maxWorkers=2 --testPathIgnorePatterns="<rootDir>/__tests__/api/"
        env:
          DATABASE_URL: file:./test.db
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  # Build Job
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Next.js application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-output
          path: .next/
          retention-days: 1

  # Deploy Preview for Pull Requests
  deploy-preview:
    name: Deploy Preview (PR)
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.event_name == 'pull_request'
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.preview-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Deploy to Vercel Preview
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "### Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "Preview URL: $DEPLOYMENT_URL" >> $GITHUB_STEP_SUMMARY

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Deployment Preview\n\nYour preview deployment is ready!\n\nURL: ${{ steps.deploy.outputs.preview-url }}\n\nPlease test the changes before merging.`
            })

  # Deploy Production for Master/Main Branch
  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    environment:
      name: Production
      url: https://vacation-planner.vercel.app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Database Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
        continue-on-error: false

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Deploy to Vercel Production
        id: deploy
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }})
          echo "production-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "### Production Deployment" >> $GITHUB_STEP_SUMMARY
          echo "Production URL: $DEPLOYMENT_URL" >> $GITHUB_STEP_SUMMARY

      - name: Verify Deployment Health
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          DEPLOYMENT_URL="${{ steps.deploy.outputs.production-url }}"

          # If DEPLOYMENT_URL is empty, try the known production URL
          if [ -z "$DEPLOYMENT_URL" ]; then
            DEPLOYMENT_URL="https://vacationplanner-theta.vercel.app"
            echo "Using fallback URL: $DEPLOYMENT_URL"
          fi

          echo "Testing deployment at: $DEPLOYMENT_URL"
          HTTP_STATUS=$(curl -L -o /dev/null -s -w "%{http_code}\n" "$DEPLOYMENT_URL")
          echo "Received HTTP status code: $HTTP_STATUS"

          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 400 ]; then
            echo "✅ Deployment health check passed with status code: $HTTP_STATUS"
            exit 0
          else
            echo "❌ Health check failed with status code: $HTTP_STATUS"
            echo "Fetching deployment logs for debugging..."
            curl -L -v "$DEPLOYMENT_URL" || true
            exit 1
          fi

  # Database Seed Job (Manual trigger only)
  seed-database:
    name: Seed Database
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Database Seed
        run: npm run db:seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
